source 'http://rubygems.org'

gem 'rails', '3.0.9'

gem 'sqlite3'


# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

gem "bcrypt-ruby", :require => "bcrypt"

gem "devise"
#gem 'omniauth'
gem 'oa-core'
gem 'oa-oauth'
gem 'tabs_on_rails'
gem 'nifty-generators'


# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:

# group :development, :test do
#   gem 'webrat'


# end
