source 'http://rubygems.org'

gem 'rails'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19', :require => 'ruby-debug'

gem "bcrypt-ruby", :require => "bcrypt"
gem 'sqlite3'
gem "devise"
gem 'oa-core'
gem 'oa-oauth'
gem 'oa-openid'
gem 'oauth-plugin', ">= 0.4.0.pre1"
gem 'tabs_on_rails'
gem 'nifty-generators'
gem 'ruby-debug19'
gem 'jquery-rails', '>= 1.0.12'
gem 'rdf'
gem 'rdf-raptor'
gem 'rest-client'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:

group :development, :test do
  gem 'webrat'
  gem 'database_cleaner'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'rspec-rails'
  gem 'pickle'
  gem 'fakeweb'

end
